version: "3.9"
services:
  db:
    image: mysql
    container_name: citylistmysql
    volumes:
      - ./city-list-database/mysql:/var/lib/mysql
    ports:
      - 3307:3306
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: youshallpass
      MYSQL_DATABASE: citylist
      MYSQL_USER: citylistapp
      MYSQL_PASSWORD: appshallpass
  coreapi:
    image: gishan/city-list-core-api
    container_name: citylistcoreapi
    ports:
      - 8082:8082
    depends_on:
      - db
    restart: unless-stopped
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: citylistapp
      MYSQL_PASSWORD: appshallpass
  web:
    image: gishan/city-list-web
    container_name: citylistweb
    ports:
      - 3000:3000
    depends_on:
      - coreapi
    restart: unless-stopped
    environment:
      CORE_API_HOST: coreapi
      CORE_API_PORT: 8082