version: "3.9"
services:
  db:
#    platform: linux/x86_64
    image: mysql
    container_name: citylistmysql
    volumes:
      - ./city-list-database/mysql:/var/lib/mysql
    ports:
      - 3307:3306
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: youshallpass
      MYSQL_DATABASE: citylist
      MYSQL_USER: citylistapp
      MYSQL_PASSWORD: appshallpass