export const SET_AUTH_DATA = "SET_AUTH_DATA";
export const SET_IS_FAILED_TO_LOAD_AUTH_DATA =
  "SET_IS_FAILED_TO_LOAD_AUTH_DATA";

export const SET_RETRIEVING_TOKEN = "SET_RETRIEVING_TOKEN";
export const SET_RETRIEVING_TOKEN_SUCCESS = "SET_RETRIEVING_TOKEN_SUCCESS";
export const SET_RETRIEVING_TOKEN_FAILURE = "SET_RETRIEVING_TOKEN_FAILURE";

export const SET_VALID_TOKEN = "SET_VALID_TOKEN";
export const SET_VALIDATING_TOKEN = "SET_VALIDATING_TOKEN";
export const SET_VALIDATING_TOKEN_SUCCESS = "SET_VALIDATING_TOKEN_SUCCESS";
export const SET_VALIDATING_TOKEN_FAILURE = "SET_VALIDATING_TOKEN_FAILURE";

export const REMOVE_AUTH_DATA = "REMOVE_AUTH_DATA";
export const SET_REMOVING_TOKEN = "SET_REMOVING_TOKEN";
export const SET_REMOVING_TOKEN_SUCCESS = "SET_REMOVING_TOKEN_SUCCESS";
export const SET_REMOVING_TOKEN_FAILURE = "SET_REMOVING_TOKEN_FAILURE";
