export const SET_CITIES_COUNT_DATA = 'SET_CITIES_COUNT_DATA';
export const SET_CITIES_PAGE_DATA = 'SET_CITIES_PAGE_DATA';
export const SET_SELECTED_CITY_DATA = 'SET_SELECTED_CITY_DATA';

export const SET_IS_FAILED_TO_LOAD_CITIES_DATA = "SET_IS_FAILED_TO_LOAD_CITIES_DATA";
export const SET_RETRIEVING_CITIES_SUCCESS = "SET_RETRIEVING_CITIES_SUCCESS";
export const SET_RETRIEVING_CITIES_FAILURE = "SET_RETRIEVING_CITIES_FAILURE";
export const SET_RETRIEVING_CITIES_DATA = "SET_RETRIEVING_CITIES_DATA";
