export const SET_CITIES_PAGE_DATA = "SET_CITIES_PAGE_DATA";
export const SET_CITIES_DATA = "SET_CITIES_DATA";
export const SET_SELECTED_CITY_DATA = "SET_SELECTED_CITY_DATA";

export const SET_CITY_EDIT = "SET_CITY_EDIT";
export const SET_CITY_VIEW = "SET_CITY_VIEW";

export const SET_SELECTED_CITY_UPDATE = "SET_SELECTED_CITY_UPDATE";
export const SET_SELECTED_CITY_UPDATE_SUCCESS =
  "SET_SELECTED_CITY_UPDATE_SUCCESS";
export const SET_SELECTED_CITY_UPDATE_FAILURE =
  "SET_SELECTED_CITY_UPDATE_FAILURE";
export const SET_SELECTED_CITY_UPDATING = "SET_SELECTED_CITY_UPDATING";

export const SET_IS_FAILED_TO_LOAD_CITIES_DATA =
  "SET_IS_FAILED_TO_LOAD_CITIES_DATA";
export const SET_RETRIEVING_CITIES_SUCCESS = "SET_RETRIEVING_CITIES_SUCCESS";
export const SET_RETRIEVING_CITIES_FAILURE = "SET_RETRIEVING_CITIES_FAILURE";
export const SET_RETRIEVING_CITIES_DATA = "SET_RETRIEVING_CITIES_DATA";
